version: '3.9'
services:
  project.notify.fakesmtp:
    image: gessnerfl/fake-smtp-server
    container_name: "project.notify.fakesmtp"
    hostname: "fakesmtp"
    ports:
      - "8025:8025"
      - "1083:8080"
  project.notify.rabbitmq:
    image: rabbitmq:3.11-management
    container_name: project.notify.rabbitmq
    ports:
      - '1088:15672'
      - '5672:5672'
    environment:
      RABBITMQ_DEFAULT_USER: RABBITMQ_DEFAULT_USER
      RABBITMQ_DEFAULT_PASS: RABBITMQ_DEFAULT_PASS
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 10s
      timeout: 5s
      retries: 5

  project.notify.mongodb:
    image: mongo
    container_name: project.notify.mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: MONGO_INITDB_ROOT_USERNAME
      MONGO_INITDB_ROOT_PASSWORD: MONGO_INITDB_ROOT_PASSWORD
      MONGO_INITDB_DATABASE: MONGO_INITDB_DATABASE
    ports:
      - 27020:27017
    volumes:
      - project.notify.mongodb:/data/db
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/project-notify --quiet
      interval: 10s
      timeout: 10s
      retries: 5

  project.notify.mongodb.ui:
    image: mongo-express
    restart: always
    container_name: project.notify.mongodb.ui
    ports:
      - 8083:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: test
      ME_CONFIG_MONGODB_URL: mongodb://admin:test@project.notify.mongodb:27017/

volumes:
  project.notify.mongodb:
